# Generated by Django 2.1.7 on 2019-04-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=100)),
                ('sort_no', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='mobile',
            field=models.CharField(default='default@qq.com', max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='tel',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
